version: '3.6'

services:
#BACKEND API
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /user/src/smart-brain-api
    env_file:
      - .env
    links:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./:/user/src/smart-brain-api
#DB
  postgres:
    env_file:
      - .env
    build: ./postgres
    ports:
      - "5432:5432"
#Redis
  redis:
    image: redis
    ports:
      - "6379:6379"