version: '3.6'

services:
#BACKEND API
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /user/src/smart-brain-api
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: viktor93
      POSTGRES_DB: smart-brain
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./:/user/src/smart-brain-api
#DB
  postgres:
    environment:
      POSTGRES_PASSWORD: viktor93
      POSTGRES_DB: smart-brain
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
    build: ./postgres
    ports:
      - "5432:5432"
  #Redis
  redis:
    image: redis
    ports:
      - "6379:6379"